apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-cicd
  labels:
    app: nodejs-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-cicd
  template:
    metadata:
      labels:
        app: nodejs-cicd
    spec:
      containers:
      - name: nodejs-cicd
        image: your-docker-image:latest
        ports:
        - containerPort: 3000
